### ISSUE TITLE
Add a feature to stingify typeof === 'object' so it will be treated as a string not as series of params

### ISSUE THREAD

**Issue by mariocoski** [5app/dare#109]
As mentioned in the PR: https://github.com/5app/dashboard/pull/6754

Any values passed to Dare api which are a type of object should be stringified.

**Comment by MrSwitch** [comment]
I'd like to approach this in two ways:

- [ ] By default object props should throw an error when inserted/modified. 
        - This is to allow future object handling.
- [ ] In the schema field attributes we could allow the content to be described as a `type: 'json'`.
        - Objects would be serialised when set and deserialised when retrieved.
