### ISSUE TITLE
Returning strings from SQL reqs regardless of vartype in DB

### ISSUE THREAD

**Issue by cboyce183** [5app/dare#32]
- Variables stored as integers or booleans in SQL are being returned as strings via DARE.
- Expected behaviour is to return them as the same type stored - or equivalent JS type.

- Dare endpoint doesnt typecheck nested results.
- Typecast ints eg: +"0"

**Comment by MrSwitch** [comment]
It would be simple to do with the new JSON functions in MySQL 5.7. However the support for MySQL 5.6 is still required. 😢
